apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ssr
  namespace: ganatan-dev
  labels:
    app: angular-ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-ssr
  template:
    metadata:
      labels:
        app: angular-ssr
    spec:
      containers:
        - name: angular-ssr
          image: registry.gitlab.com/ganatan/sandbox/angular-ssr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: angular-ssr-service
  namespace: ganatan-dev
  labels:
    app: angular-ssr
spec:
  selector:
    app: angular-ssr
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: angular-ssr-route
  namespace: ganatan-dev
  labels:
    app: angular-ssr
spec:
  to:
    kind: Service
    name: angular-ssr-service
  port:
    targetPort: 4000
  tls:
    termination: edge
