workflow:
  rules:
    - changes:
        - angular-bootstrap/**/*
        - angular-ssr/**/*
        - rag-generator/frontend-angular/**/*
        - rag-generator/backend-springboot/**/*
    - when: never

stages:
  - trigger

trigger-angular-bootstrap:
  stage: trigger
  trigger:
    include: .gitlab/angular-bootstrap-ci.yml
  rules:
    - changes:
        - angular-bootstrap/**/*

trigger-angular-ssr:
  stage: trigger
  trigger:
    include: .gitlab/angular-ssr-ci.yml
  rules:
    - changes:
        - angular-ssr/**/*

trigger-rag-generator-frontend-angular:
  stage: trigger
  trigger:
    include: .gitlab/rag-generator-frontend-angular-ci.yml
  rules:
    - changes:
        - rag-generator/frontend-angular/**/*

trigger-rag-generator-backend-springboot:
  stage: trigger
  trigger:
    include: .gitlab/rag-generator-backend-springboot-ci.yml
  rules:
    - changes:
        - rag-generator/backend-springboot/**/*

