SHOW CON_NAME;

ALTER SESSION
SET
  CONTAINER = XEPDB1;

CREATE USER admin_user IDENTIFIED BY "Trustno1" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE SEQUENCE TO admin_user;