DROP TABLE RAG_PERSON CASCADE CONSTRAINTS;
DROP TABLE RAG_CITY CASCADE CONSTRAINTS;
DROP TABLE RAG_COUNTRY CASCADE CONSTRAINTS;
DROP TABLE RAG_CONTINENT CASCADE CONSTRAINTS;

DROP SEQUENCE RAG_PERSON_ID_SEQ;
DROP SEQUENCE RAG_CITY_ID_SEQ;
DROP SEQUENCE RAG_COUNTRY_ID_SEQ;
DROP SEQUENCE RAG_CONTINENT_ID_SEQ;
