-- =========================
-- CONTINENTS
-- =========================
INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('AF', 'Africa-oracle', 'Africa', 30370000, 1287920000, 54);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('AN', 'Antarctica-oracle', 'Antarctica', 14000000, 4490, 0);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('AS', 'Asia-oracle', 'Asia', 44579000, 4545133000, 47);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('OC', 'Australia-oracle', 'Australia_(continent)', 8600000, 41261000, 14);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('EU', 'Europe-oracle', 'Europe', 10180000, 742648000, 45);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('NA', 'North America-oracle', 'North_America', 24709000, 587615000, 23);

INSERT INTO RAG_CONTINENT (CODE, NAME, WIKIPEDIA_LINK, AREA, POPULATION, COUNTRIES_NUMBER) 
VALUES ('SA', 'South America-oracle', 'South_America', 17840000, 428240000, 12);

-- =========================
-- COUNTRIES
-- =========================
INSERT INTO RAG_COUNTRY (NAME, WIKIPEDIA_LINK, ISO_NUMERIC, ISO_ALPHA2, ISO_ALPHA3, FLAG, CONTINENT_ID) 
VALUES('United States','United_States','840','US','USA','us.png',
 (SELECT ID FROM RAG_CONTINENT WHERE CODE='NA'));

INSERT INTO RAG_COUNTRY (NAME, WIKIPEDIA_LINK, ISO_NUMERIC, ISO_ALPHA2, ISO_ALPHA3, FLAG, CONTINENT_ID) 
VALUES('Jersey','Jersey','832','JE','JEY','je.png',
 (SELECT ID FROM RAG_CONTINENT WHERE CODE='EU'));

INSERT INTO RAG_COUNTRY (NAME, WIKIPEDIA_LINK, ISO_NUMERIC, ISO_ALPHA2, ISO_ALPHA3, FLAG, CONTINENT_ID) 
VALUES('Sweden','Sweden','752','SE','SWE','se.png',
 (SELECT ID FROM RAG_CONTINENT WHERE CODE='EU'));

-- =========================
-- CITIES
-- =========================
INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('New York','New_York_City',0,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='840'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Modesto','Modesto,_California',0,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='840'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Syracuse','Syracuse,_New_York',0,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='840'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Saint Helier','Saint_Helier',0,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='832'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Stockholm','Stockholm',1,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='752'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Fresno','Fresno,_California',1,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='840'));

INSERT INTO RAG_CITY (NAME, WIKIPEDIA_LINK, CAPITAL, COUNTRY_ID) 
VALUES('Detroit','Detroit',1,
 (SELECT ID FROM RAG_COUNTRY WHERE ISO_NUMERIC='840'));

-- =========================
-- PERSONS
-- =========================
INSERT INTO RAG_PERSON (NAME, WIKIPEDIA_LINK, BIRTH_DATE, BIRTH_CITY_ID) 
VALUES('Robert Downey Jr.','Robert_Downey_Jr.', TO_DATE('1965-04-04','YYYY-MM-DD'),
 (SELECT ID FROM RAG_CITY WHERE WIKIPEDIA_LINK='New_York_City'));

INSERT INTO RAG_PERSON (NAME, WIKIPEDIA_LINK, BIRTH_DATE, BIRTH_CITY_ID) 
VALUES('Jeremy Renner','Jeremy_Renner', TO_DATE('1971-01-07','YYYY-MM-DD'),
 (SELECT ID FROM RAG_CITY WHERE WIKIPEDIA_LINK='Modesto,_California'));
